---

vagrant_provider: "virtualbox"

net_shell: &net_shell
  # add custom default router
  #- "route add default gw 192.168.10.1"
  # delete virtualbox default gw 10.0.2.2
  #- "eval `route -n | awk '{ if ($2 == \"10.0.2.2\") print \"route del default gw \" $2; }'`"

servers:
  - name: puppet-master
    ssh_username: ubuntu
    virtualbox:
      box_name: ubuntu/xenial64
      box_hostname: puppet-master
      cpus: 1
      memory: 1024
      private_network:
        ip: "192.168.10.11"
      ports:
        - {guest: 80, host: 1180}
      shell_inline: *net_shell

  - name: puppet-agent
    ssh_username: ubuntu
    virtualbox:
      box_name: ubuntu/xenial64
      box_hostname: puppet-agent
      cpus: 1
      memory: 1024
      private_network:
        ip: "192.168.10.12"
      ports:
        - {guest: 80, host: 1280}
      shell_inline: *net_shell

  - name: ansible-fake
    ssh_username: ubuntu
    virtualbox:
      box_name: ubuntu/xenial64
      box_hostname: ansible-fake
      cpus: 1
      memory: 1024
      private_network:
        ip: "192.168.10.10"
      ports:
        - {guest: 80, host: 1080}
      shell_inline: *net_shell
    ansibles:
      - playbook: "ansible/vagrant-puppet.yml"
        verbose: "vvvv"
        limit: 'all:!ansible-fake'
        tags: "all"
        groups:
          puppet_master_nodes: ["puppet-master"]
          puppet_agent_nodes: ["puppet-agent"]
        extra_vars:
          manage_interface: "enp0s8"
          puppet_agent_server: "puppet-master"
