---

- hosts: all
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_pipelining: false
  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes
      become: yes
      ignore_errors: true

    - name: install python2
      raw: test -e /usr/bin/python || sudo apt-get -y install python-minimal
      become: yes
  tasks:
    - name: Remove requiretty in sudoers set, which makes pipelining fail
      lineinfile:
        regexp: '^\w+\s+requiretty'
        dest: /etc/sudoers
        state: absent

- hosts: all
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_pipelining: true
    manage_interface: "eth0"
  tasks:
    - name: Build hosts file if inventory entry is defined with hostname
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item]['ansible_%s'|format(manage_interface)]['ipv4']['address'] }} {{ hostvars[item].ansible_hostname }}"
        state: present
      with_items: "{{ ansible_play_hosts }}"

- hosts: puppet_master_nodes
  become: yes
  roles:
    - {role: puppet, puppet_server_install: true}

- hosts: puppet_agent_nodes
  become: yes
  roles:
    - {role: puppet, puppet_server_install: false}
